import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="max-w-[1000px] m-auto bg-gray-50">
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="p-6 bg-gray-50 md:border border-b">
        <h2 className="text-2xl font-semibold select-none">MyTodos</h2>
      </header>
      <main className='border-b'>
        <section className="p-6 border-l border-r">
          <form className='flex flex-row bg-white border'>
            <input type="text" className="ml-2 w-full outline-none" placeholder="Buy Tomatoes" />
            <input type="submit" className="p-2 ml-auto bg-blue-500 text-white hover:bg-blue-600 cursor-pointer" value="Add Todo"/>
          </form>
          <p className="mt-4 p-2 bg-blue-400 rounded-md text-white select-none">Loading...</p>
        </section>
        <section className='flex flex-col gap-2 px-6 border-l border-r mb-4'>
          <div className="card">
            <div className="card__wrapper flex justify-between p-4 border bg-white">
              <p className='text-lg font-semibold'>Buy milk for the family</p>
              <button className="text-blue-600">Complete</button>
            </div>
          </div>
          <div className="card">
            <div className="card__wrapper flex justify-between p-4 border bg-white">
              <p className='text-lg font-semibold'>Buy milk for the family</p>
              <button className="text-blue-600">Complete</button>
            </div>
          </div>
          <div className="card">
            <div className="card__wrapper flex justify-between p-4 border bg-white">
              <p className='text-lg font-semibold'>Buy milk for the family</p>
              <button className="text-blue-600">Complete</button>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

export default Home
