import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="max-w-[1000px] m-auto">
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="p-6 bg-gray-50 border-b">
        <h2 className="text-2xl font-semibold">MyTodos</h2>
      </header>
      <main>
        <section className="p-6">
          <form className='flex flex-row bg-white border'>
            <input type="text" className="ml-2 w-full outline-none" placeholder="Buy Tomatoes" />
            <input type="submit" className="p-2 ml-auto bg-blue-500 text-white hover:bg-blue-600 cursor-pointer" value="Add Todo"/>
          </form>
        </section>
      </main>
    </div>
  )
}

export default Home
