import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import TodoForm from '../components/TodoForm';
import TodoList from '../components/TodoList';

const Home: NextPage = () => {
  return (
    <div className='max-w-[1000px] m-auto bg-gray-50'>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className='border-b'>
        <TodoForm />
        <TodoList />
      </main>
    </div>
  );
};

export default Home;
